# Generated by Django 3.0.5 on 2020-04-15 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Postado')),
                ('set_date', models.DateTimeField(auto_now=True, verbose_name='atualizado')),
            ],
        ),
    ]
